[package]
name = "oxyroot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
log = "0.4.17"
num = "0.4.0"
uuid = "1.0.0"
thiserror = "1.0"
chrono = "0.4.19"
flate2 = "1.0"
lazy_static = "1.4.0"
trait-set = "0.3.0"
#as-any = "0.3.0"
downcast = "0.11.0"
num-traits = "0.2"
num-derive = "0.3"
regex = "1"
xz2 = "0.1"
itertools = "0.10.2"

[dev-dependencies]
test-log = "0.2.10"
env_logger = "*"
