[package]
name = "test_suite"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxyroot = { path = "../oxyroot", features = ["derive"] }
anyhow = "1"